#!/bin/bash

function logpipe {
  n=$1

  if [[ $n == 1 ]];then
    while read x; do echo "bluh"; echo $x; done
  else
    while read x; do echo "blah"; echo $x;done
  fi
}

tee >( logpipe 1 ) >( logpipe 2) > /dev/null
